version: "3.4"

services:
  app:
    image: frontend
    volumes:
      - ./src:/app/src
    build: 
      context: .
      dockerfile: Dockerfile.test #Dockerfile.prod
      args:
        - REACT_APP_CONTRACT_ADDRESS=${REACT_APP_CONTRACT_ADDRESS}
    ports:
      - "5000:3000" #5000:80
    restart: unless-stopped
    env_file:
      - ./.env
