version: "3.4"

services:
  app:
    image: frontend
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_CONTRACT_ADDRESS=${REACT_APP_CONTRACT_ADDRESS}
    ports:
      - "5000:80" #5000:80
    restart: unless-stopped
    env_file:
      - ./.env.prod
